name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: 'go.mod'
    - name: Setup Ko
      uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
      with:
        version: v0.18.0
    - name: Build and push image
      run: ko build --bare --tags=latest --tags=${{ github.ref_name }} --tag-only --sbom=cyclonedx
